### ISSUE TITLE
"look_at_emitter" in 2Dtrail doesn't work

### ISSUE THREAD

**Issue by Skyfrit** [LeonardMeagher2/GodotAssets#4]
I get those errors when I set "look_at_emitter" to true.

![image 1](https://user-images.githubusercontent.com/20874456/41819242-a0e45b5a-77ef-11e8-9a19-64c22674c060.jpg)

**Comment by LeonardMeagher2** [comment]
Will fix it today

**Comment by Skyfrit** [comment]
Thanks, also thank you for providing those scripts.
